package mocks

import "github.com/stretchr/testify/mock"

// Shorten is an autogenerated mock type for Shorten type
type Shorten struct {
	mock.Mock
}

type MyMap struct {
}

// GenerateUniqueID provides a mock function with given fields: _a0
func (_m *Shorten) GenerateUniqueID(_a0 MyMap) []byte {
	ret := _m.Called(_a0)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(MyMap) []byte); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).([]byte)
	}

	return r0
}

type mockConstructorTestingTNewShorten interface {
	mock.TestingT
	Cleanup(func())
}

// NewShorten creates a new instance of Shorten. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewShorten(t mockConstructorTestingTNewShorten) *Shorten {
	mock := &Shorten{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
